sudo: false
language:
  node_js

node_js:
  - '9'
  - '8'
  - '6'

script:
  - npm run ci # webpack@4
  - npm install npm install webpack@^3.0.0
  - npm run ci # webpack@3

after_success:
  npm run cover
