unit_tests: &unit_tests
  steps:
    - checkout
    - setup_remote_docker
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: NPM Rebuild
        command: npm rebuild
    - run:
        name: Run unit tests.
        command: npm run test

version: 2
jobs:
  dependency_cache:
    docker:
      - image: circleci/node:9.6.1-browsers
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  node9_webpack_latest:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: NPM Rebuild
          command: npm rebuild
      - run:
          name: Run unit tests.
          command: npm run test
      - run:
          name: Submit coverage data to codecov.
          command: npm run cover
          when: on_success

  node8_webpack_latest:
    docker:
      - image: circleci/node:9.6.1-browsers
    <<: *unit_tests

  node6_webpack_latest:
    docker:
      - image: circleci/node:6.13.0-stretch-browsers
    <<: *unit_tests

  analysis:
    docker:
      - image: circleci/node:9.6.1-browsers
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: NPM Rebuild
          command: npm rebuild
      - run:
          name: Run linting.
          command: npm run lint
      # - run:
      #     name: Run NSP Security Check.
      #     command: npm run security
      # - run:
      #     name: Validate Commit Messages
      #     command: npm run ci:lint:commits

version: 2.0
workflows:
  version: 2
  run-tests:
    jobs:
      - dependency_cache
      - node9_webpack_latest:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      - node8_webpack_latest:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      - node6_webpack_latest:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      - analysis:
          requires:
            - node9_webpack_latest
            - node8_webpack_latest
            - node6_webpack_latest
          filters:
            tags:
              only: /.*/
